export const UPDATE_ACTIVE_EVENT = 'UPDATE_CURRENT_EVENT';

export const UPDATE_TIME_AVAILABLE = 'UPDATE_TIME_AVAILABLE';

export const ADD_SKILLS = 'ADD_SKILLS';
export const REMOVE_SKILLS = 'REMOVE_SKILLS';

export const UPDATE_SKILLS = 'UPDATE_SKILLS';
export const  UPDATE_RERENDER_MYTASKS = 'UPDATE_RERENDER_MYTASKS';
export const UPDATE_ALL_TASKS = 'UPDATE_ALL_TASKS';
export const ASSIGN_USER_TO_TASK = 'ASSIGN_USER_TO_TASK';

export const  REMOVE_SUGGESTED_TASK = 'REMOVE_SUGGESTED_TASK';
export const ADD_TO_MY_TASK = 'ADD_TO_MY_TASK';