export const UPDATE_ACTIVE_EVENT = 'UPDATE_CURRENT_EVENT';

export const UPDATE_TIME_AVAILABLE = 'UPDATE_TIME_AVAILABLE';

export const ADD_SKILLS = 'ADD_SKILLS';
export const REMOVE_SKILLS = 'REMOVE_SKILLS';

export const UPDATE_SKILLS = 'UPDATE_SKILLS';
export const  UPDATE_RERENDER_MYTASKS = 'UPDATE_RERENDER_MYTASKS'